
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

public class NewJFrame extends javax.swing.JFrame {

    static ArrayList<Usuarios> Global = new ArrayList();

    public NewJFrame() {
        initComponents();
        Compro(Global);
        Login.setSize(400, 250);
        Login.setLocationRelativeTo(Base);
        Login.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SingIn = new javax.swing.JFrame();
        label2 = new java.awt.Label();
        OpcionesDeTipoDeUsuario = new java.awt.Choice();
        label5 = new java.awt.Label();
        nombreUSU = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        nombreVeri = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        Contra = new javax.swing.JPasswordField();
        label6 = new java.awt.Label();
        ConfirmContra = new javax.swing.JPasswordField();
        Salir = new java.awt.Button();
        LogIN = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        label7 = new java.awt.Label();
        NombreUwu = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        ContrasenyaUwU = new javax.swing.JPasswordField();
        Empezar = new java.awt.Button();
        Tipos = new java.awt.Choice();
        Salida = new java.awt.Button();
        MenuOyentes = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Albums");
        DefaultMutableTreeNode node1 = new DefaultMutableTreeNode("Canciones");
        root.add(node2);
        Arbolito1 = new javax.swing.JTree(root);
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista1 = new javax.swing.JList<>();
        AgregarListas = new java.awt.Button();
        VerListas = new java.awt.Button();
        EliminarListas = new java.awt.Button();
        MODListas = new java.awt.Button();
        label9 = new java.awt.Label();
        Salir1 = new java.awt.Button();
        MenuArtista = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        Arbolito2 = new javax.swing.JTree();
        AgregarAListas = new java.awt.Button();
        WacharSongs = new java.awt.Button();
        EliminarSongs = new java.awt.Button();
        AgregarSongs = new java.awt.Button();
        ModSongs = new java.awt.Button();
        AddLists = new java.awt.Button();
        WacharLists = new java.awt.Button();
        DesaparecerLists = new java.awt.Button();
        MODOLISTS = new java.awt.Button();
        Salide = new java.awt.Button();
        Login = new javax.swing.JFrame();
        Base = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        Salide1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();

        SingIn.setBackground(new java.awt.Color(0, 204, 0));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setForeground(new java.awt.Color(204, 255, 204));
        label2.setText("Sing-In");

        label5.setForeground(new java.awt.Color(0, 0, 0));
        label5.setText("Ingrese su nombre de usuario: ");

        label4.setForeground(new java.awt.Color(0, 0, 0));
        label4.setText("Confirme");

        label3.setForeground(new java.awt.Color(0, 0, 0));
        label3.setText("Ingrese su contrasenya");

        label6.setForeground(new java.awt.Color(0, 0, 0));
        label6.setText("Confirme");

        Salir.setBackground(new java.awt.Color(153, 0, 0));
        Salir.setName(""); // NOI18N

        javax.swing.GroupLayout SingInLayout = new javax.swing.GroupLayout(SingIn.getContentPane());
        SingIn.getContentPane().setLayout(SingInLayout);
        SingInLayout.setHorizontalGroup(
            SingInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SingInLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(SingInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmContra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpcionesDeTipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SingInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(SingInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Contra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(nombreUSU, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreVeri, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SingInLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SingInLayout.setVerticalGroup(
            SingInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SingInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreVeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(OpcionesDeTipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Log-In");

        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Ingrese su nombre de usuario: ");

        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("Ingrese su contrasenya");

        Empezar.setLabel("Empieze");
        Empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpezarActionPerformed(evt);
            }
        });

        Tipos.add("");
        Tipos.add("Artistas");
        Tipos.add("Oyente");

        Salida.setBackground(new java.awt.Color(153, 0, 0));
        Salida.setName(""); // NOI18N

        javax.swing.GroupLayout LogINLayout = new javax.swing.GroupLayout(LogIN.getContentPane());
        LogIN.getContentPane().setLayout(LogINLayout);
        LogINLayout.setHorizontalGroup(
            LogINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogINLayout.createSequentialGroup()
                .addGroup(LogINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogINLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(LogINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Empezar, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(Tipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContrasenyaUwU)
                            .addComponent(NombreUwu))
                        .addGap(80, 80, 80)
                        .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LogINLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel2)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        LogINLayout.setVerticalGroup(
            LogINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogINLayout.createSequentialGroup()
                .addGroup(LogINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LogINLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(LogINLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreUwu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContrasenyaUwU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(Tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addComponent(Empezar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        MenuOyentes.setFocusable(false);
        MenuOyentes.setName("MenuOyentes"); // NOI18N

        jLabel4.setText("Listas de reproduccion");

        jScrollPane1.setViewportView(Arbolito1);

        jLabel3.setText("Listas Canciones likeadas");

        Lista1.setModel(new javax.swing.AbstractListModel<String>() {

            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return (Oyentes)Global.get(i).lista de canciones; }
        });
        jScrollPane2.setViewportView(Lista1);

        AgregarListas.setLabel("Agregar Listas");

        VerListas.setLabel("Ver Listas");

        EliminarListas.setLabel("Eliminar Listas");

        MODListas.setLabel("MOD Listas");
        MODListas.setName(""); // NOI18N
        MODListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODListasActionPerformed(evt);
            }
        });

        label9.setText("Menu");

        Salir1.setBackground(new java.awt.Color(153, 0, 0));
        Salir1.setName(""); // NOI18N

        javax.swing.GroupLayout MenuOyentesLayout = new javax.swing.GroupLayout(MenuOyentes.getContentPane());
        MenuOyentes.getContentPane().setLayout(MenuOyentesLayout);
        MenuOyentesLayout.setHorizontalGroup(
            MenuOyentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuOyentesLayout.createSequentialGroup()
                .addGroup(MenuOyentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuOyentesLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(MenuOyentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(MenuOyentesLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MenuOyentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgregarListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EliminarListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VerListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MODListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(61, 61, 61)
                        .addGroup(MenuOyentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MenuOyentesLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOyentesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuOyentesLayout.setVerticalGroup(
            MenuOyentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuOyentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuOyentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MenuOyentesLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuOyentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MenuOyentesLayout.createSequentialGroup()
                                .addComponent(AgregarListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VerListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliminarListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MODListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MenuOyentesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(Salir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane3.setViewportView(Arbolito2);

        AgregarAListas.setLabel("Agregar Listas");
        AgregarAListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAListasActionPerformed(evt);
            }
        });

        WacharSongs.setLabel("Ver Canciones");

        EliminarSongs.setLabel("Eliminar Canciones");

        AgregarSongs.setLabel("Agregar Canciones");

        ModSongs.setLabel("MOD Canciones");
        ModSongs.setName(""); // NOI18N

        AddLists.setLabel("Agregar Listas");

        WacharLists.setLabel("Ver Listas");
        WacharLists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WacharListsActionPerformed(evt);
            }
        });

        DesaparecerLists.setLabel("Eliminar Listas");

        MODOLISTS.setLabel("MOD Listas");
        MODOLISTS.setName(""); // NOI18N

        Salide.setBackground(new java.awt.Color(153, 0, 0));
        Salide.setName(""); // NOI18N
        Salide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuArtistaLayout = new javax.swing.GroupLayout(MenuArtista.getContentPane());
        MenuArtista.getContentPane().setLayout(MenuArtistaLayout);
        MenuArtistaLayout.setHorizontalGroup(
            MenuArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuArtistaLayout.createSequentialGroup()
                        .addGroup(MenuArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarAListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarSongs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WacharSongs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarSongs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModSongs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DesaparecerLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WacharLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MODOLISTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuArtistaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Salide, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        MenuArtistaLayout.setVerticalGroup(
            MenuArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuArtistaLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(MenuArtistaLayout.createSequentialGroup()
                        .addComponent(AgregarAListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WacharSongs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EliminarSongs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgregarSongs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModSongs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(AddLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WacharLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DesaparecerLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MODOLISTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        Login.setPreferredSize(new java.awt.Dimension(382, 245));

        Base.setPreferredSize(new java.awt.Dimension(382, 245));
        Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setLabel("Sing-in");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        Base.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        button2.setLabel("Log-In");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        Base.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 65, -1));

        Salide1.setBackground(new java.awt.Color(153, 0, 0));
        Salide1.setName(""); // NOI18N
        Salide1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salide1ActionPerformed(evt);
            }
        });
        Base.add(Salide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 30, -1));

        jLabel1.setText("Bienvenido");
        Base.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 78, 30));

        label1.setForeground(new java.awt.Color(204, 204, 255));
        label1.setName(""); // NOI18N
        label1.setText("Ingrese la opcion adecuada a su ingrese");
        Base.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login.getContentPane());
        Login.getContentPane().setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MODListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODListasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MODListasActionPerformed

    private void WacharListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WacharListsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WacharListsActionPerformed

    private void Salide1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salide1ActionPerformed
        dispose();
    }//GEN-LAST:event_Salide1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        Login.setVisible(false);
        SingIn.setSize(463, 383);
        SingIn.setLocationRelativeTo(null);
        SingIn.setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        Login.setVisible(false);
        LogIN.setSize(463, 383);
        LogIN.setLocationRelativeTo(null);
        LogIN.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    private void EmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpezarActionPerformed
        String paca1, paca2, paca3;
        paca1 = NombreUwu.getText();
        paca2 = ContrasenyaUwU.getSelectedText();
        paca3 = Tipos.getSelectedItem();

        if ((paca3.equalsIgnoreCase("Artistas")) || (paca3.equalsIgnoreCase("Oyentes"))) {
            for (int i = 0; i < Global.size(); i++) {
                if ((Global.get(i).getNombreUWU().equals(paca1)) && (Global.get(i).getContNYA().equals(paca2))) {
                    if ((Global.get(i) instanceof Artistas)) {
                        Login.setVisible(false);
                        MenuArtista.setSize(800, 700);
                        MenuArtista.setLocationRelativeTo(null);
                        MenuArtista.setVisible(true);
                    }
                    if ((Global.get(i) instanceof Oyentes)) {
                        Login.setVisible(false);
                        MenuOyentes.setSize(800, 700);
                        MenuOyentes.setLocationRelativeTo(null);
                        MenuOyentes.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_EmpezarActionPerformed

    private void SalideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalideActionPerformed

    }//GEN-LAST:event_SalideActionPerformed

    private void AgregarAListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAListasActionPerformed
        String mam1 = JOptionPane.showInputDialog(MenuArtista, "Ingrese el nuevo nombre de la Lista");
        ArrayList<Canciones> List = new ArrayList();
        for (int i = 0; i < 1; i++) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea Ingresar canciones?");
            if (opcion == JOptionPane.YES_OPTION) {
                i--;
                String man = JOptionPane.showInputDialog(MenuArtista, "Ingrese el  nombre de la Cancion");
                String man2 = JOptionPane.showInputDialog(MenuArtista, "Ingrese la duracion de la Cancion");
                double man2p0 = Double.parseDouble(man2);
                Canciones new1= new Canciones(man, man2p0,mam1);
                List.add(new1);
            } else {
                i++;
            }
        }
        ListasDeRepro pas = new ListasDeRepro(List, mam1);
    }//GEN-LAST:event_AgregarAListasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame();
            }
        });
    }

    public static void Vendo(ArrayList<Usuarios> Compro) {
File archivo = new File("Cosas_Guardades.txt");
        try (FileWriter fw = new FileWriter(archivo, true)) {
            for (int i = 0; i < Global.size(); i++) {
            fw.write(Global.get(i).toString());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    
        
    }

    public static ArrayList<Usuarios> Compro(ArrayList<Usuarios> Compro) {

        return Compro;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button AddLists;
    private java.awt.Button AgregarAListas;
    private java.awt.Button AgregarListas;
    private java.awt.Button AgregarSongs;
    private javax.swing.JTree Arbolito1;
    private javax.swing.JTree Arbolito2;
    private javax.swing.JPanel Base;
    private javax.swing.JPasswordField ConfirmContra;
    private javax.swing.JPasswordField Contra;
    private javax.swing.JPasswordField ContrasenyaUwU;
    private java.awt.Button DesaparecerLists;
    private java.awt.Button EliminarListas;
    private java.awt.Button EliminarSongs;
    private java.awt.Button Empezar;
    private javax.swing.JList<String> Lista1;
    private javax.swing.JFrame LogIN;
    private javax.swing.JFrame Login;
    private java.awt.Button MODListas;
    private java.awt.Button MODOLISTS;
    private javax.swing.JFrame MenuArtista;
    private javax.swing.JFrame MenuOyentes;
    private java.awt.Button ModSongs;
    private javax.swing.JTextField NombreUwu;
    private java.awt.Choice OpcionesDeTipoDeUsuario;
    private java.awt.Button Salida;
    private java.awt.Button Salide;
    private java.awt.Button Salide1;
    private java.awt.Button Salir;
    private java.awt.Button Salir1;
    private javax.swing.JFrame SingIn;
    private java.awt.Choice Tipos;
    private java.awt.Button VerListas;
    private java.awt.Button WacharLists;
    private java.awt.Button WacharSongs;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTextField nombreUSU;
    private javax.swing.JTextField nombreVeri;
    // End of variables declaration//GEN-END:variables
}
